# Generated by Django 2.2.28 on 2024-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('calories', models.IntegerField(verbose_name='Калории')),
            ],
            options={
                'verbose_name': 'Меню доставки',
                'verbose_name_plural': 'Меню доставки',
                'db_table': 'MenuItems',
                'ordering': ['name'],
            },
        ),
    ]
