# Generated by Django 2.2.28 on 2024-04-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_menuitem_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], default=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MenuItem', verbose_name='Позиция в меню')),
            ],
            options={
                'verbose_name': 'Отзыв к блюду',
                'verbose_name_plural': 'Отзывы к блюдам',
                'db_table': 'Review',
                'ordering': ['rating'],
            },
        ),
    ]
